#!/bin/sh

# ~/.xprofile

#check and source zsh
[[ -f ~/.config/zsh/.zshenv ]] && source ~/.config/zsh/.zshenv

# keyboard
-model pc105 -layout us,us,tr -variant ,dvorak,f -option grp:caps_toggle

# run programs with & to background
#exec /home/$USER/bin/urxvtd 
